import type { StatusTarget } from '../src/lib/status/types.ts'

type State = {
  uf: string
  name: string
  capital: string
  detran: string
  government: string
  cityHall: string
}

export const STATES: State[] = [
  {
    uf: 'AC',
    name: 'Acre',
    capital: 'Rio Branco',
    detran: 'https://www.detran.ac.gov.br/',
    government: 'https://www.ac.gov.br/',
    cityHall: 'https://www.riobranco.ac.gov.br/',
  },
  {
    uf: 'AL',
    name: 'Alagoas',
    capital: 'Maceió',
    detran: 'https://www.detran.al.gov.br/',
    government: 'https://alagoas.al.gov.br/',
    cityHall: 'https://www.maceio.al.gov.br/',
  },
  {
    uf: 'AP',
    name: 'Amapá',
    capital: 'Macapá',
    detran: 'https://www.detran.ap.gov.br/',
    government: 'https://www.portal.ap.gov.br/',
    cityHall: 'https://macapa.ap.gov.br/',
  },
  {
    uf: 'AM',
    name: 'Amazonas',
    capital: 'Manaus',
    detran: 'https://www.detran.am.gov.br/',
    government: 'https://www.amazonas.am.gov.br/',
    cityHall: 'https://www.manaus.am.gov.br/',
  },
  {
    uf: 'BA',
    name: 'Bahia',
    capital: 'Salvador',
    detran: 'https://www.detran.ba.gov.br/',
    government: 'https://www.ba.gov.br/',
    cityHall: 'https://www.salvador.ba.gov.br/',
  },
  {
    uf: 'CE',
    name: 'Ceará',
    capital: 'Fortaleza',
    detran: 'https://www.detran.ce.gov.br/',
    government: 'https://www.ceara.gov.br/',
    cityHall: 'https://www.fortaleza.ce.gov.br/',
  },
  {
    uf: 'DF',
    name: 'Distrito Federal',
    capital: 'Brasília',
    detran: 'https://www.detran.df.gov.br/',
    government: 'https://www.df.gov.br/',
    cityHall: 'https://www.agenciabrasilia.df.gov.br/',
  },
  {
    uf: 'ES',
    name: 'Espírito Santo',
    capital: 'Vitória',
    detran: 'https://detran.es.gov.br/',
    government: 'https://www.es.gov.br/',
    cityHall: 'https://www.vitoria.es.gov.br/',
  },
  {
    uf: 'GO',
    name: 'Goiás',
    capital: 'Goiânia',
    detran: 'https://www.detran.go.gov.br/',
    government: 'https://goias.gov.br/',
    cityHall: 'https://www.goiania.go.gov.br/',
  },
  {
    uf: 'MA',
    name: 'Maranhão',
    capital: 'São Luís',
    detran: 'https://www.detran.ma.gov.br/',
    government: 'https://www.ma.gov.br/',
    cityHall: 'https://www.saoluis.ma.gov.br/',
  },
  {
    uf: 'MT',
    name: 'Mato Grosso',
    capital: 'Cuiabá',
    detran: 'https://www.detran.mt.gov.br/',
    government: 'https://www.mt.gov.br/',
    cityHall: 'https://www.cuiaba.mt.gov.br/',
  },
  {
    uf: 'MS',
    name: 'Mato Grosso do Sul',
    capital: 'Campo Grande',
    detran: 'https://www.detran.ms.gov.br/',
    government: 'https://www.ms.gov.br/',
    cityHall: 'https://www.campogrande.ms.gov.br/',
  },
  {
    uf: 'MG',
    name: 'Minas Gerais',
    capital: 'Belo Horizonte',
    detran: 'https://transito.mg.gov.br/',
    government: 'https://www.mg.gov.br/',
    cityHall: 'https://prefeitura.pbh.gov.br/',
  },
  {
    uf: 'PA',
    name: 'Pará',
    capital: 'Belém',
    detran: 'https://www.detran.pa.gov.br/',
    government: 'https://www.pa.gov.br/',
    cityHall: 'https://prefeitura.belem.pa.gov.br/',
  },
  {
    uf: 'PB',
    name: 'Paraíba',
    capital: 'João Pessoa',
    detran: 'https://detran.pb.gov.br/',
    government: 'https://paraiba.pb.gov.br/',
    cityHall: 'https://www.joaopessoa.pb.gov.br/',
  },
  {
    uf: 'PR',
    name: 'Paraná',
    capital: 'Curitiba',
    detran: 'https://www.detran.pr.gov.br/',
    government: 'https://www.parana.pr.gov.br/',
    cityHall: 'https://www.curitiba.pr.gov.br/',
  },
  {
    uf: 'PE',
    name: 'Pernambuco',
    capital: 'Recife',
    detran: 'https://www.detran.pe.gov.br/',
    government: 'https://www.pe.gov.br/',
    cityHall: 'https://www2.recife.pe.gov.br/',
  },
  {
    uf: 'PI',
    name: 'Piauí',
    capital: 'Teresina',
    detran: 'https://www.detran.pi.gov.br/',
    government: 'https://www.pi.gov.br/',
    cityHall: 'https://pmt.pi.gov.br/',
  },
  {
    uf: 'RJ',
    name: 'Rio de Janeiro',
    capital: 'Rio de Janeiro',
    detran: 'https://www.detran.rj.gov.br/',
    government: 'https://www.rj.gov.br/',
    cityHall: 'https://prefeitura.rio/',
  },
  {
    uf: 'RN',
    name: 'Rio Grande do Norte',
    capital: 'Natal',
    detran: 'https://www.detran.rn.gov.br/',
    government: 'https://www.rn.gov.br/',
    cityHall: 'https://www.natal.rn.gov.br/',
  },
  {
    uf: 'RS',
    name: 'Rio Grande do Sul',
    capital: 'Porto Alegre',
    detran: 'https://www.detran.rs.gov.br/',
    government: 'https://estado.rs.gov.br/',
    cityHall: 'https://prefeitura.poa.br/',
  },
  {
    uf: 'RO',
    name: 'Rondônia',
    capital: 'Porto Velho',
    detran: 'https://www.detran.ro.gov.br/',
    government: 'https://rondonia.ro.gov.br/',
    cityHall: 'https://www.portovelho.ro.gov.br/',
  },
  {
    uf: 'RR',
    name: 'Roraima',
    capital: 'Boa Vista',
    detran: 'https://www.detran.rr.gov.br/',
    government: 'https://portal.rr.gov.br/',
    cityHall: 'https://boavista.rr.gov.br/',
  },
  {
    uf: 'SC',
    name: 'Santa Catarina',
    capital: 'Florianópolis',
    detran: 'https://www.detran.sc.gov.br/',
    government: 'https://www.sc.gov.br/',
    cityHall: 'https://www.pmf.sc.gov.br/',
  },
  {
    uf: 'SP',
    name: 'São Paulo',
    capital: 'São Paulo',
    detran: 'https://www.detran.sp.gov.br/',
    government: 'https://www.sp.gov.br/',
    cityHall: 'https://www.prefeitura.sp.gov.br/',
  },
  {
    uf: 'SE',
    name: 'Sergipe',
    capital: 'Aracaju',
    detran: 'https://www.detran.se.gov.br/',
    government: 'https://www.se.gov.br/',
    cityHall: 'https://www.aracaju.se.gov.br/',
  },
  {
    uf: 'TO',
    name: 'Tocantins',
    capital: 'Palmas',
    detran: 'https://www.to.gov.br/detran',
    government: 'https://www.to.gov.br/',
    cityHall: 'https://www.palmas.to.gov.br/',
  },
]

const FEDERAL: [string, string, string][] = [
  ['govbr', 'Portal gov.br', 'https://www.gov.br/pt-br'],
  ['login-govbr', 'Login gov.br (acesso.gov.br)', 'https://sso.acesso.gov.br/'],
  ['meu-inss', 'Meu INSS', 'https://meu.inss.gov.br/'],
  ['ecac', 'e-CAC (Receita Federal)', 'https://cav.receita.fazenda.gov.br/autenticacao/login'],
  ['receita-servicos', 'Serviços da Receita Federal', 'https://servicos.receitafederal.gov.br/'],
  ['regularize', 'Regularize (PGFN)', 'https://www.regularize.pgfn.gov.br/'],
  ['meu-sus', 'Meu SUS Digital', 'https://meususdigital.saude.gov.br/'],
  [
    'senatran',
    'Portal de Serviços Senatran (CNH Digital)',
    'https://portalservicos.senatran.serpro.gov.br/',
  ],
  ['pf-passaporte', 'Passaporte (Polícia Federal)', 'https://servicos.dpf.gov.br/'],
  ['ctps', 'Carteira de Trabalho Digital', 'https://servicos.mte.gov.br/'],
  ['caixa', 'Caixa (FGTS, benefícios)', 'https://www.caixa.gov.br/'],
  ['cadunico', 'Cadastro Único', 'https://cadunico.dataprev.gov.br/'],
  ['bcb', 'Banco Central (Pix, Registrato)', 'https://www.bcb.gov.br/'],
  ['registrato', 'Registrato', 'https://registrato.bcb.gov.br/'],
  ['enem', 'Enem (Inep)', 'https://enem.inep.gov.br/'],
  ['tse', 'Justiça Eleitoral (título de eleitor)', 'https://www.tse.jus.br/'],
  ['consumidor', 'Consumidor.gov.br', 'https://www.consumidor.gov.br/'],
  ['falabr', 'Fala.BR (ouvidoria)', 'https://falabr.cgu.gov.br/'],
  ['transparencia', 'Portal da Transparência', 'https://portaldatransparencia.gov.br/'],
  ['esocial', 'eSocial', 'https://login.esocial.gov.br/'],
  ['nfse', 'NFS-e Nacional', 'https://www.nfse.gov.br/EmissorNacional'],
  ['ibge', 'IBGE', 'https://www.ibge.gov.br/'],
  ['correios', 'Correios', 'https://www.correios.com.br/'],
]

export function curatedTargets(): StatusTarget[] {
  return [
    ...FEDERAL.map(([id, name, url]) => ({
      id: `federal:${id}`,
      group: 'federal' as const,
      name,
      url,
    })),
    ...STATES.flatMap((state) => [
      {
        id: `detran:${state.uf}`,
        group: 'detran' as const,
        name: `Detran-${state.uf}`,
        url: state.detran,
        uf: state.uf,
      },
      {
        id: `estado:${state.uf}`,
        group: 'estado' as const,
        name: `Governo do ${state.name}`,
        url: state.government,
        uf: state.uf,
      },
      {
        id: `capital:${state.uf}`,
        group: 'capital' as const,
        name: state.uf === 'DF' ? 'Brasília (Agência Brasília)' : `Prefeitura de ${state.capital}`,
        url: state.cityHall,
        uf: state.uf,
        city: state.capital,
      },
    ]),
  ]
}
